project:
  type: website
  output-dir: docs

website:
  title: "W. Jonas Reger<br>Data Science"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: pages/about.qmd
        text: Experience
      - pages/pvalue-calculator.qmd
      - posts.qmd

format:
  html:
    theme:
      - assets/styles/darkbay.scss
    css: assets/styles/styles.css
    toc: true



